#!/usr/bin/env node
/** Build the offline, interactive review gallery with the same generator as the demo. */
import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const [out]=process.argv.slice(2);if(!out)throw Error('Usage: node material-gallery.mjs NEW_OUTPUT.html');
const base=fileURLToPath(new URL('.',import.meta.url));
const js=await build({entryPoints:[base+'material-gallery.js'],bundle:true,write:false,minify:true,format:'iife',legalComments:'inline'});
const license=await readFile(base+'node_modules/three/LICENSE','utf8');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RoomKit material collection</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f3ee;color:#242925;font:15px system-ui,sans-serif}header,main{max-width:1600px;margin:auto;padding:28px 36px}header{padding-bottom:16px}h1{font-size:32px;letter-spacing:-1px;margin:4px 0 10px}header p{color:#63685f;margin:6px 0;max-width:900px;line-height:1.5}.eyebrow{font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#6b735f}nav{display:flex;gap:14px;flex-wrap:wrap;align-items:end;margin-top:22px}label{display:grid;gap:5px;font-size:12px;color:#59624f}input,select,button{background:white;border:1px solid #c8cbbf;border-radius:6px;padding:8px;color:#293426;font:inherit}input{width:120px}button{cursor:pointer}button:hover{background:#e6eddd}#grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}article{overflow:hidden;background:#fff;border:1px solid #dedfd5;border-radius:10px}article img{display:block;width:100%;aspect-ratio:26/21;object-fit:cover;background:#e3e1dd}.caption{padding:14px}h2{font-size:17px;margin:0 0 6px}.caption p{font-size:12px;color:#606858;min-height:32px;margin:0 0 8px;line-height:1.5}.caption button{font-size:12px;padding:5px 8px}#status{font-size:12px;color:#68745f;margin-top:14px}@media(max-width:1000px){#grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:500px){header,main{padding:20px 16px}h1{font-size:28px}#grid{grid-template-columns:1fr}}</style>
<header><div class="eyebrow">RoomKit / procedural collection</div><h1>Materials & surface finishes</h1><p>Twenty-three seeded materials, including stone, wood, fabrics, leather, glass and glazed ceramics. Glass reveals the patterned background; compare surfaces under the same studio lighting or inspect their base color.</p>
<nav><label>Collection<select id="version"><option value="3">Full collection</option><option value="2">Upgraded originals</option><option value="1">Original</option></select></label><label>Show<select id="family"><option value="new">Extended collection</option><option value="all">All materials</option><option value="glass">Glass</option><option value="ceramic">Porcelain / ceramics</option><option value="wall">Wall finishes</option><option value="travertine">Travertine</option><option value="terrazzo">Terrazzo</option><option value="linen">Linen</option><option value="leather">Leather</option></select></label><label>View<select id="mode"><option value="pbr">Lit material</option><option value="color">Base color</option></select></label><label>Seed<input id="seed" value="review-17" maxlength="100"></label><label>Texture size<select id="resolution"><option>256</option><option selected>512</option><option>1024</option></select></label><button id="random">New seed</button></nav><div id="status" role="status">Loading…</div></header><main><div id="grid"></div></main>
<script>${js.outputFiles[0].text.replaceAll('</script','<\\/script')}\n/* ${license.replaceAll('*/','* /')} */</script></html>`;
await writeFile(out,html,{flag:'wx'});console.log(out);
